# Generated by Django 4.0.4 on 2022-04-19 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Author_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('publication_date', models.DateField()),
                ('publisher', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('updated_at', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author_register.author')),
            ],
        ),
    ]
